# Generated by Django 4.2.7 on 2023-12-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmt_app', '0002_alter_reservation_guest_alter_reservation_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
